subroutine SwashPrintGridInfo
!
!   --|-----------------------------------------------------------|--
!     | Delft University of Technology                            |
!     | Faculty of Civil Engineering and Geosciences              |
!     | Environmental Fluid Mechanics Section                     |
!     | P.O. Box 5048, 2600 GA  Delft, The Netherlands            |
!     |                                                           |
!     | Programmer: Marcel Zijlema                                |
!   --|-----------------------------------------------------------|--
!
!
!     SWASH (Simulating WAves till SHore); a non-hydrostatic wave-flow model
!     Copyright (C) 2010-2026  Delft University of Technology
!
!     This program is free software: you can redistribute it and/or modify
!     it under the terms of the GNU General Public License as published by
!     the Free Software Foundation, either version 3 of the License, or
!     (at your option) any later version.
!
!     This program is distributed in the hope that it will be useful,
!     but WITHOUT ANY WARRANTY; without even the implied warranty of
!     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
!     GNU General Public License for more details.
!
!     You should have received a copy of the GNU General Public License
!     along with this program. If not, see <http://www.gnu.org/licenses/>.
!
!
!   Authors
!
!    1.00: Marcel Zijlema
!
!   Updates
!
!    1.00, March 2023: New subroutine
!
!   Purpose
!
!   Prints some relevant information concerning the mesh
!
!   Modules used
!
    use ocpcomm4
    use SwanGriddata
    use SwanGridobjects
!
    implicit none
!
!   Local variables
!
    integer, save                         :: ient = 0  ! number of entries in this subroutine
    integer                               :: iface     ! loop counter over faces
    integer                               :: ncellsi   ! number of internal cells
    integer                               :: nfacesi   ! number of internal faces
    !
    real                                  :: avegsiz   ! average gridsize
    real                                  :: gridsize  ! actual gridsize of cell
    real                                  :: npav      ! counter for computing average gridsize
    real                                  :: rdx       ! reciprocal of distance between circumcenters adjacent to face
    !
    character(80), dimension(2)           :: helptxt   ! auxiliary textlines
    !
    type(celltype), dimension(:), pointer :: cell      ! datastructure for cells with their attributes
    type(facetype), dimension(:), pointer :: face      ! datastructure for faces with their attributes
!
!   Structure
!
!   Description of the pseudo code
!
!   Source text
!
    if (ltrace) call strace (ient,'SwashPrintGridInfo')
    !
    ! point to cell and face objects
    !
    cell => gridobject%cell_grid
    face => gridobject%face_grid
    !
    if ( grid_generator == meth_adcirc ) then
       !
       ! grid is generated by SMS/ADCIRC
       !
       write (helptxt(1),'(a)') 'solely triangles'
       write (helptxt(2),'(a)') 'SMS/ADCIRC'
       !
    elseif ( grid_generator == meth_triangle ) then
       !
       ! grid is generated by Triangle
       !
       write (helptxt(1),'(a)') 'solely triangles'
       write (helptxt(2),'(a)') 'Triangle'
       !
    elseif ( grid_generator == meth_easy ) then
       !
       ! grid is generated by Easymesh
       !
       write (helptxt(1),'(a)') 'solely triangles'
       write (helptxt(2),'(a)') 'Easymesh'
       !
    else
       !
       write (helptxt(1),'(a)') 'triangles or hybrid cells'
       write (helptxt(2),'(a)') 'unknown'
       !
    endif
    !
    ! determine number of internal faces and internal cells
    !
    nfacesi = nfaces - nfacesb
    ncellsi = ncells - ncellsb
    !
    ! write some constant with respect to the grid to PRINT file
    !
    write(PRINTF,100) trim(helptxt(1)), trim(helptxt(2)), nverts, ncells, &
                      ncellsi, ncellsb, nfaces, nfacesi, nfacesb
    !
    ! determine minimum, maximum and average gridsize of the grid
    !
    mingsiz = 1.0e10
    maxgsiz = 0.0
    avegsiz = 0.
    npav    = 0.
    !
    do iface = 1, nfaces
       !
       if ( face(iface)%atti(FMARKER) == 0 ) then   ! internal face
          !
          ! reciprocal of distance between adjacent centroids of current face
          !
          rdx = face(iface)%attr(FACEDISTG)
          !
          if ( rdx /= 0. ) then
             !
             ! compute gridsize relevant to discretization
             !
             gridsize = 1./rdx
             !
             ! compute minimum, maximum and average gridsize
             !
             if ( gridsize < mingsiz ) then
                mingsiz = gridsize
             elseif ( gridsize > maxgsiz ) then
                maxgsiz = gridsize
             endif
             !
             avegsiz = avegsiz + gridsize
             npav    = npav    + 1.
             !
          endif
          !
       endif
       !
    enddo
    !
    avegsiz = avegsiz / npav
    !
    write(PRINTF,200) mingsiz
    write(PRINTF,300) maxgsiz
    write(PRINTF,400) avegsiz
    !
    ! format statements
    !
 100 format(// ' The unstructured grid contains ',a,' generated by ',a//      &
               ' Number of vertices          = ',i7//                         &
               ' Number of cells             = ', i7/                         &
               '    Number of internal cells = ', i7/                         &
               '    Number of boundary cells = ',i7//                         &
               ' Number of faces             = ',i7/                          &
               '    Number of internal faces = ',i7/                          &
               '    Number of boundary faces = ',i7//)
 200 format(' The minimum gridsize =',f12.5)
 300 format(' The maximum gridsize =',f12.5)
 400 format(' The average gridsize =',f12.5)
    !
end subroutine SwashPrintGridInfo
